name: Application CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Build docker compose
        run: docker-compose up -d app-test testingdb redistestdb
      - name: Check lint
        run: make check_lint
      - name: Run tests
        run: make unit_tests
      - name: Take down containers
        run: make stop
